const TESTS = [
    'Adenosine Deaminase (ADA)',
    'SGPT / ALT',
    'Albumin',
    'Alkaline Phosphatase (ALP)',
    'Amylase',
    'SGOT / AST',
    'Bilirubin Total (Direct & Indirect)',
    'Bilirubin Total',
    'Blood Urea Nitrogen (BUN)',
    'Calcium',
    'Creatine Phosphokinase (CPK)',
    'Creatinine',
    'Sodium, Potassium, Chloride',
    'Estimated Glomerular Filtration Rate',
    'Gamma-Glutamyl Transferase (GGT)',
    'Glucose Challenge Test (GCT)',
    'Fasting Plasma Glucose',
    'Creatine Kinase MB',
    'Glucose Post Prandial',
    'Glucose Random',
    'Glucose Tolerance Test (GTT-2)',
    'HbA1c (Glycosylated Hemoglobin)',
    'Iron Studies',
    'Lactate Dehydrogenase (LDH)',
    'Lipase',
    'Microalbuminuria, Spot Urine',
    'Phosphorus',
    'Blood Urea Nitrogen (BUN), Urea',
    'Potassium',
    'Protein / Creatinine Ratio',
    'Sodium',
    'Total Cholesterol',
    'Uric Acid',
    'Alpha-Fetoprotein (AFP)',
    'Anti Cyclic Citrullinated Peptide Antibodies (Anti CCP)',
    'Progesterone',
    'Prolactin (PRL)',
    'Prostate Specific Antigen (PSA) Total',
    'Parathyroid Hormone (PTH)',
    'QUADRUPLE MARKER TEST',
    'Testosterone Total',
    'Anti Mullerian Hormone (AMH)',
    'TSH 3rd Generation',
    'Vitamin B12',
    'Vitamin D 25-Hydroxy',
    'LF, FSH',
    'Anti Thyroid Peroxidase Antibodies (TPO)',
    'CA 125',
    'Carcinoembryonic Antigen (CEA)',
    'Serum Cortisol',
    'DOUBLE MARKER',
    'Vitamin Check',
    'Estradiol (E2)',
    'Ferritin',
    'Folic Acid',
    'Follicle-Stimulating Hormone (FSH)',
    'Thyroid Profile Free',
    'FT4, TSH 3rd Gen',
    'FT4 (Free Thyroxine 4)',
    'Homocysteine',
    'LH + FSH + PRL',
    'IgE Total',
    'Insulin Fasting',
    'Luteinizing Hormone (LH)',
    'APTT',
    'BT, CT Time',
    'Prothrombin Time',
    'D-Dimer (Quantitative)',
    'Cerebrospinal Fluid (CSF) Analysis',
    'Pleural Fluid Analysis',
    'Semen Analysis',
    'Stool Occult Blood',
    'Stool Routine & Microscopic Examination',
    'Urine Pregnancy Test (UPT)',
    'Urine Routine & Microscopy',
    'Fine Needle Aspiration Cytology (FNAC)',
    'PAP (Papanicolaou) Smear',
    'Liquid Based Cytology (LBC)',
    'Sure Path Cytology',
    'Cytology For Malignant Cells',
    'HLA B27',
    'Flowcytometry',
    'Absolute Eosinophil Count (AEC)',
    'Blood Grouping, Rh (D) Typing',
    'Haemogram with PS',
    'Complete Blood Count (CBC)',
    'Erythrocyte Sedimentation Rate (ESR)',
    'Haemoglobin (Hb)',
    'Indirect Coombs Test (ICT) Serum',
    'Malaria Antigen Detection, Rapid',
    'Malaria Parasite (MP) Smear',
    'Peripheral Blood Smear Examination',
    'Platelet Count',
    'Reticulocyte Count',
    'TLC, DLC (Differential Leucocyte Count)',
    'Hemoglobin Variant (Hb Electrophoresis)',
    'CBC, ESR | TLC (Total Leucocyte Count)',
    'DLC (Differential Leucocyte Count)',
    'Histopathology: Large Tissue Biopsy',
    'Histopathology: Medium Tissue Biopsy',
    'Histopathology: Small Tissue Biopsy',
    'Return Of Paraffin Block / Slide',
    'COVID-19 Virus Qualitative RT PCR',
    'Hepatitis B (HBV) Viral Load By Real Time PCR',
    'Hepatitis C (HCV) Viral Load By Real Time PCR',
    'Acid Fast Bacilli (AFB) Smear',
    'Gram Stain',
    'Mantoux / Tuberculin Sensitivity Test',
    'Culture-Aerobic Paediatric Blood-Bactec',
    'Culture, Sputum',
    'Culture, Urine',
    'Culture, Aerobic Blood-Bactec',
    'Genexpert Ultra MTB/RIF',
    'Culture, Semen',
    'Culture Aerobic, Pus',
    'Ante Natal Profile Basic',
    'Diabescreen',
    'Fever Panel- 1',
    'Lipid Profile Direct',
    'Pathotest Advance',
    'Pathotest Platinum',
    'Liver & Kidney Profile',
    'Liver Function Advanced',
    'Basic Liver Panel',
    'Fever Panel Basic',
    'Kidney Profile',
    'Kidney Function Test (KFT)',
    'ANC Panel',
    'Pre Operative Panel',
    'Vitamin D Panel',
    'LBC + HPV',
    'Fertikind Complete',
    'Pathotest Complete',
    'Lipid Screen',
    'Pathotest Lite',
    'Pathotest Active',
    'Fever Screen',
    'Ante Natal Profile 1',
    'Pathotest Total',
    'Pathotest Screen',
    'Fertikind Total',
    'Liver Function Test (LFT)',
    'Surgical Profile',
    'Anti Streptolysin O (ASO), Quantitative',
    'C-Reactive Protein (CRP), Quantitative',
    'Dengue Duo Rapid Test',
]

export default function PopularHealthTests() {
    return (
        <section className="w-full py-6 sm:py-8">
            <h2 className="text-lg sm:text-xl font-extrabold text-[#2b2d37] mb-4">
                Popular Health Tests
            </h2>
            <p className="text-sm sm:text-[15px] text-gray-600 leading-loose">
                {TESTS.map((test, i) => (
                    <span key={test}>
                        <a
                            href="#"
                            className="hover:text-[#194b76] hover:underline transition-colors"
                        >
                            {test}
                        </a>
                        {i < TESTS.length - 1 && (
                            <span className="mx-1.5 text-gray-300 select-none">|</span>
                        )}
                    </span>
                ))}
            </p>
        </section>
    )
}
